Добавил eslint, prettier, husky и lint-staged в create-react-app
denisov-ie/admin-app pull request #1
Opened 2022-09-09 00:49 UTC by denisov-ie

Прошу проверить.
Настраивал по: 
- https://dev.to/eprikhodko/eslint-prettier-vs-code-create-react-app-airbnb-52bc
- https://typicode.github.io/husky/#/
- https://prettier.io/docs/en/install.html
- https://github.com/okonet/lint-staged

2022-09-09 17:43 UTC, Muslik requested changes
Доработать

2022-09-09 17:43 UTC, Muslik commented on .husky/pre-commit
> +npm run lint-staged
Все хорошо, только сюда бы еще eslint добавить. Чтобы вы не пушили с ошибками eslint-а файлы. Сейчас если запустить npm start, у вас вываливаются ошибки.

2022-09-11 21:41 UTC, denisov-ie commented on .husky/pre-commit
> +npm run lint-staged
Поправил, спасибо.

2022-09-12 08:49 UTC, Muslik requested changes
prettier не срабатывает на jsx файлы

2022-09-13 20:15 UTC, Muslik approved these changes

2022-10-08 12:15 UTC, merged