2. Собрать шапку страницы на mocks - сделано.
denisov-ie/admin-app pull request #2
Opened 2022-10-18 02:00 UTC by denisov-ie

Все компоненты юай-кита перенесены на реакт. Шапка страницы готова, фильтры открываются и закрываются, кнопочки на инпутах и серчбаре работают, работает смена темы.

2022-10-19 00:15 UTC, denisov-ie commented on src/components/shared/Dropdown/Dropdown.jsx
> +            <label key={keys[index]}>
@Muslik, помоги понять, плз, почему, если использовать генератор уникального id из lodash, то при скрытии/показе элемента крыжики пропадают, а если использовать индекс child из children, то остаются?

2022-10-25 08:27 UTC, makhnatkin commented on src/components/shared/Dropdown/Dropdown.jsx
> +            <label key={keys[index]}>
чтобы понять – выведите код в консоль, посмотри что приходит
```
 {children.map((child, index) => 
{
     console.log('index', keys[index]);      
     return (<label key={keys[index]}>)

}
```
ну и в целом брать ключ из объекта ключей по индексу - мало смысла, по сути тоже самое, что и индексы
https://reactjs.org/docs/reconciliation.html#keys

2022-10-29 13:09 UTC, Muslik requested changes
Рассмотрели на уроке

2022-11-01 01:30 UTC, Muslik requested changes
Убрали стейт из инпута, затащили его в Searchbar )))
В Button text -> children

Ну и будет видео разбор.

2022-11-01 10:04 UTC, makhnatkin commented on src/components/context/FilterContext/FilterContext.jsx
> +  const handleFilterClear = useCallback(
нужен ли тут useCallback?
когда они нужны, а когда нет?

2022-11-01 10:04 UTC, makhnatkin commented on src/components/context/FilterContext/FilterContext.jsx
> +  const [filters, setFilters] = useState(getDefaultFilters());
лучше заменить getDefaultFilters() на initialState

2022-11-01 10:04 UTC, makhnatkin commented on src/components/context/FilterContext/FilterContext.jsx
> +  const value = useMemo(
нужно ли useMemo?
https://frontend-stuff.com/blog/understanding-when-use-usememo/#почему-бы-тогда-не-использовать-usememo-везде

2022-11-01 10:04 UTC, makhnatkin commented on src/components/modules/AmountFilter/AmountFilter.jsx
> +        externalOnClearListener={() =>
externalOnClearListener – плохое имя пропса
во первых почему external
во вторых слово Listener не принятно использовать в именах пропс

2022-11-04 21:54 UTC, Muslik approved these changes

2022-11-05 00:24 UTC, merged